server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://postgres_pilot:5432/pilots
    username: sga
    password: sga
  jpa:
    hibernate:
      ddl-auto: update
---      
spring:
  profiles: kubernetes
  datasource:
    url: jdbc:postgresql://postgres-pilots:5432/pilots


