server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/pilots
    username: sga
    password: sga
  jpa:
    hibernate:
      ddl-auto: create
