server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/city
    username: sga
    password: sga
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
